// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeToggle from "@/components/Auth/theme-toggle"; // new component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-white text-black dark:bg-gray-900 dark:text-white transition-colors duration-300`}
      >
        <ThemeToggle /> {/* insert client theme toggle button */}
        {children}
      </body>
    </html>
  );
}
